name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: |
          (New-Object System.Net.WebClient).DownloadFile("https://github.com/upx/upx/releases/download/v3.96/upx-3.96-win64.zip",$(Get-Location).Path+"\upx.zip");
          7z e upx.zip -r -o".\" upx.exe
      - run: |
          go install github.com/tc-hib/go-winres@latest
          go-winres simply --icon public/favicon.png
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
